USE SisVentas;
CREATE TABLE TBL_CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(100),
    FECHA_REGISTRO DATE,
    INGRESOS FLOAT,
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_VENTAS (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    FECHA DATE,
    TOTAL FLOAT,
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_EMPLEADOS (
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(100),
    FECHA_INGRESO DATE,
    SALARIO FLOAT,
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_VENTAS_DETALLE (
    ID_VENTA_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENTA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2)
);

CREATE TABLE TBL_PRODUCTOS (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ID_MARCA INT,
    PRECIO DECIMAL(10,2),
    STOCK INT,
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_MARCAS (
    ID_MARCA SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE TABLE TBL_COMPRAS (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROVEEDOR INT,
    FECHA DATE,
    TOTAL DECIMAL(10,2),
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_COMPRAS_DETALLE (
    ID_COMPRA_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPRA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2)
);

CREATE TABLE TBL_PROVEEDORES (
    ID_PROVEEDOR SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(100),
    FECHA_CAMBIO DATETIME
);

CREATE TABLE TBL_PUESTOS (
    ID_PUESTO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);
